[workspace]
members = [
    'pallets/bitcoin-vaults',
    'pallets/confidential-docs',
    'pallets/rbac',
    'pallets/fruniques',
    'pallets/gated-marketplace',
]
[profile.release]
panic = 'unwind'
