
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inova-n2-network
  namespace: hashed-network
spec:
  replicas: 1
  serviceName: inova-n2-network-headless
  selector:
    matchLabels:
      app: inova-n2-network
  template:
    metadata:
      namespace: hashed-network
      labels:
        app: inova-n2-network
    spec:
      containers:
      - name: inova-n2-network
        imagePullPolicy: IfNotPresent
        image: sebastianmontero/hashed-substrate-node:0e83482bfce70e5392aaa9101a16bd1b8c9ef1bd
        command: ["/var/www/hashed-substrate/scripts/run-node.sh"]
        args: ["inovaSpecRaw.json", "/var/www/hashed/node-data"]
        volumeMounts:
          - name: inova-n2-pvc
            mountPath:  /var/www/hashed/node-data
        env:
          - name: BOOTNODES
            value: "/dns/inova-n1-network.hashed-network.svc.cluster.local/tcp/30333/p2p/12D3KooWRNsn75iQuPz4AAq6B64351z9u2LLSsdsxEjDy5vgJV9t"
          - name: MNEMO
            valueFrom:
              secretKeyRef:
                name: inova-n2-secrets
                key: MNEMO
                optional: false
          - name: NODEKEY
            valueFrom:
              secretKeyRef:
                name: inova-n2-secrets
                key: NODEKEY
                optional: false
        resources:
          limits:
            memory: "3G"
            cpu: "1.5"
        ports:
        - containerPort: 9933
        - containerPort: 9944
        - containerPort: 30333
  volumeClaimTemplates:
  - metadata:
      name: inova-n2-pvc
      namespace: hashed-network
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name:  inova-n2-network
  namespace: hashed-network
spec:
  selector:
    app:  inova-n2-network
  type:  ClusterIP
  ports:
  - name:  p2p-port
    port:  30333
    targetPort:  30333
  - name:  ws-port
    port:  9944
    targetPort:  9944
  - name:  rpc-port
    port:  9933
    targetPort:  9933
---
# Uncomment if a persistent volume needs to be created manually
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: md5-persistent-volume
#   namespace: hashed-network
# spec:
#   capacity:
#     storage: 20Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path: /var/www/hashed/
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: minikube.k8s.io/hostname
#               operator: In
#               values:
#               - minikube
