apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: chaos-n4-pvc-chaos-n4-network-0
    namespace: hashed-network
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
